name: test

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PGUSER: postgres
      PGPASSWORD: postgres

    steps:
      - uses: actions/checkout@v2
      - uses: exivity/actions/postgres@master
      - run: createdb -h localhost test
      - run: bash date.sh
